service: aws-express-postgres-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  environment:
    POSTGRES_HOST: !GetAtt RDSInstance.Endpoint.Address
    POSTGRES_DB: postgres
    POSTGRES_USER: myuser
    POSTGRES_PASSWORD: mypassword

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
    vpc:
      securityGroupIds:
        - !Ref LambdaSecurityGroup
      subnetIds:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2

resources:
  Resources:
    Vpc:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        InstanceTenancy: default
        Tags:
          - Key: Name
            Value: MyVPC
    PublicSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref Vpc
        CidrBlock: 10.0.1.0/24
        AvailabilityZone: ap-southeast-1a
        MapPublicIpOnLaunch: true
    PublicSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref Vpc
        CidrBlock: 10.0.2.0/24
        AvailabilityZone: ap-southeast-1b
        MapPublicIpOnLaunch: true
    DBSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: DB Subnet Group
        SubnetIds:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2
    RDSInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 20
        DBInstanceIdentifier: my-database
        DBInstanceClass: db.t3.micro
        Engine: postgres
        MasterUsername: myuser
        MasterUserPassword: mypassword
        StorageType: gp2
        VPCSecurityGroups:
          - !Ref RDSSecurityGroup
        DBSubnetGroupName:
          Ref: DBSubnetGroup
    RDSSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: RDS Security Group
        VpcId: !Ref Vpc
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 5432
            ToPort: 5432
            SourceSecurityGroupId: !GetAtt LambdaSecurityGroup.GroupId
    LambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Lambda Security Group
        VpcId: !Ref Vpc
